SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS_LIMIT = 60

PLAYER_ALIVE = False
GAME_OVER = False

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_INITIAL_SPEED = 40
ASTEROID_MAX_INITIAL_SPEED = 150

SPLIT_VELOCITY_THRESHOLD = 10.0


PLAYER_RADIUS = 20
PLAYER_MAX_ANGULAR_VELOCITY = 5
PLAYER_ANGULAR_ACCELERATION = 7
PLAYER_ANGULAR_DRAG = 0.5
ANGULAR_THRESHOLD = 0.05
PLAYER_ACCELERATION = 100
SHOOT_COOLDOWN = 0.2


SHOT_RADIUS = 5
SHOT_SPEED = 200

#Starfield
CELL_SIZE = 100